In [1]:
from pathlib import Path
from typing import Tuple
from numpy.typing import NDArray

import amazon_dataset 
import numpy as np
import pandas as pd
from scipy import sparse

DMRL_RES_PATH = Path('data/DMRL-Clothing_Shoes_and_Jewelry/best_scores.npz')
SEMMACRID_RES_PATH = Path('data/SEM-MacridVAE-Clothing_Shoes_and_Jewelry-run/eval.npz')
TRAIN_PATH = Path('data/DMRL-Clothing_Shoes_and_Jewelry/train.txt')
TEST_PATH = Path('data/DMRL-Clothing_Shoes_and_Jewelry/test.txt')
ITEMS_PATH = Path('data/DMRL-Clothing_Shoes_and_Jewelry/items.txt')
USERS_PATH = Path('data/DMRL-Clothing_Shoes_and_Jewelry/users.txt')

In [2]:
assert DMRL_RES_PATH.exists()
assert SEMMACRID_RES_PATH.exists()
assert TRAIN_PATH.exists()
assert TEST_PATH.exists()
assert ITEMS_PATH.exists()
assert USERS_PATH.exists()

#  Load all data

In [3]:
dmrl_results: NDArray[np.floating] = np.vstack(next(iter(np.load(DMRL_RES_PATH, allow_pickle=True).values())))
dmrl_results.shape

(23318, 38493)

In [4]:
sem_macrid_results: NDArray[np.floating] = next(iter(np.load(SEMMACRID_RES_PATH, allow_pickle=True).values()))
sem_macrid_results.shape

(23318, 38493)

In [5]:
assert sem_macrid_results.shape == dmrl_results.shape

Get users

In [6]:
users = pd.read_csv(USERS_PATH)
assert len(users) == sem_macrid_results.shape[0]
users

Unnamed: 0      0
0      A30NKRF3KBGA06      0
1       AL0XGCBE6Z22M      1
2       AMT5LF0TKY67C      2
3      A2BY8EVXA3NRHD      3
4       AWE6KR1ELIYQ3      4
...               ...    ...
23313  A1MFBF49ZFMH2N  23313
23314  A36AF5I7D0VO8F  23314
23315   A35ZS7JT3G9B8  23315
23316  A3GC94SEKQI3QU  23316
23317  A185C12Y9XLYGY  23317

[23318 rows x 2 columns]

Get items

In [7]:
items = pd.read_csv(ITEMS_PATH)
assert len(items) == sem_macrid_results.shape[1]
items

Unnamed: 0  item_id
0      B000B6AV7K        0
1      B0143D7EE4        1
2      B0105V2DEY        2
3      B014EY21H2        3
4      B005LUROIK        4
...           ...      ...
38488  B00A9R2P7A    38488
38489  B017HK485S    38489
38490  B008H7UKYY    38490
38491  B006K6PJTK    38491
38492  B01DUSBHZ0    38492

[38493 rows x 2 columns]

In [8]:
def load_interaction_matrix(file: Path, shape: Tuple[int, int]) -> sparse.csr_matrix:
    df = pd.read_csv(file)
    return sparse.csr_matrix(
        (np.ones_like(df['user']), (df['user'], df['item'])),
        shape=shape,
        dtype=float
    )


train = load_interaction_matrix(TRAIN_PATH, (len(users), len(items)))
test = load_interaction_matrix(TEST_PATH, (len(users), len(items)))

# Analyze results

Let's make the trained data to be zero 

In [9]:
dmrl_results[train.nonzero()] = -np.inf
sem_macrid_results[train.nonzero()] = -np.inf

Analyze how they agree in the top 5 results

In [10]:
k = 5

best_dmrl = dmrl_results.argpartition(kth=-k, axis=1)[:, -k:]
best_sem_macridvae = sem_macrid_results.argpartition(kth=-k, axis=1)[:, -k:]

In [12]:
dmrl_results.argmax(axis=1)

array([19594,  8913, 32930, ..., 24574, 13147, 34301])

Arrays are very memory intensive so we delete the original results

In [14]:
import gc
del sem_macrid_results, dmrl_results
gc.collect()

0

In [16]:
best_dmrl

array([[11253, 19594, 15314, 29368, 12176],
       [32501, 34301,  2121, 23339,  8913],
       [13181, 30484,  3235, 32930, 36164],
       ...,
       [ 3482,  6105,  4866, 14556, 24574],
       [32060,  5807, 24346, 13147, 32438],
       [ 6217, 33684, 27597, 13116, 34301]])

In [17]:
best_sem_macridvae

array([[ 8703, 10284, 26373, 38308,  1752],
       [  854, 30552, 26624, 32501, 34301],
       [ 8703, 10284,  1752, 38308, 26373],
       ...,
       [ 8703, 26373, 10284, 38308,  1752],
       [ 8703, 10284, 26373,  1752, 38308],
       [16534, 13116, 34301, 33684, 27597]])

In [46]:
best_counts_semmacridvae = pd.Series(best_sem_macridvae.flatten()).value_counts(normalize=True).to_frame('percentage').head(20)
best_counts_semmacridvae

percentage
1752     0.086302
38308    0.083978
26373    0.070135
10284    0.066121
8703     0.064560
34301    0.029874
32501    0.027481
30552    0.025868
854      0.021666
26624    0.021271
6027     0.013672
17254    0.013063
6112     0.011819
4702     0.010636
2332     0.009100
12576    0.009057
22880    0.008448
32062    0.008354
7243     0.007797
23727    0.007514

In [47]:
best_counts_dmrl = pd.Series(best_dmrl.flatten()).value_counts(normalize=True).to_frame('percentage').head(20)
best_counts_dmrl

percentage
6027     0.006896
21557    0.005412
17254    0.005344
921      0.005078
6112     0.005035
24346    0.004992
24956    0.004975
31411    0.004975
8963     0.004666
18492    0.004520
38308    0.004494
35166    0.004460
26261    0.004451
1235     0.004306
9258     0.004297
6388     0.004246
18555    0.004203
18611    0.004203
32060    0.004194
27811    0.004160

In [48]:
set(best_counts_dmrl.index) & set(best_counts_semmacridvae.index)

{6027, 6112, 17254, 38308}

In [32]:
pd.Series(best_dmrl.flatten()).value_counts() > 10

array([21799,     0,     2, ..., 38484,     3, 38482])

In [91]:
pd.Series(np.asarray(test.sum(axis=0))[0].astype(int)).sort_values(ascending=False).head(20)

18031    168
38308    165
26373    164
3520     163
8703     160
34043    153
28568    153
10284    152
6388     152
5372     146
1752     140
12593    140
13038    138
23510    131
33683    130
307      123
19838    118
35166     91
31411     82
6536      78
dtype: int64

In [21]:
pd.Series(train.sum(axis=0).tolist()[0]).sort_values(ascending=False)

12593    617.0
33683    598.0
19838    590.0
307      569.0
10284    567.0
         ...  
31833      0.0
8552       0.0
8557       0.0
8558       0.0
21618      0.0
Length: 38493, dtype: float64

In [72]:
items.iloc[2]

Unnamed: 0    B0105V2DEY
item_id                2
Name: 2, dtype: object

In [74]:
some_products = amazon_dataset.products_df('Clothing_Shoes_and_Jewelry')
some_products

asin                                        description  \
id                                                                       
47       5120053084  Top Length (Neck to Bottom Hem) Small - 29 inc...   
144      7709260373                                               None   
284      B00001TOXD  Includes One Broom. This broom goes great with...   
316      B00004U1J2  Tired of having your kid running around the ho...   
333      B00004VWJ3  Birkenstock's Black Super Birki Clog is made o...   
...             ...                                                ...   
2684954  B01HJDBMUM  When you need a fashionable shoe for your son-...   
2684955  B01HJCZ02O  Dynamic in design, the honor sneaker is comfor...   
2684979  B01HJDZM30  Part of our Performance Fishing Gear line of p...   
2684987  B01HJDVCJI  An edgy take on Adidas running-inspired herita...   
2685059  B01HJHFS58  CUPSHE Intro To inspire confidence and beauty ...   

                                                     title     brand  \
id                                                                     
47       sofsy Soft-Touch Rayon Blend Tie Front Nursing...      None   
144      LJYH Children's Collar Motorcycle Faux Leather...      LJYH   
284                                      Adult Witch Broom      None   
316                                Buzz Lightyear Jet Pack      None   
333      Birki's Super Pu, Black, 44 M EU (13 Women /11...   Birki's   
...                                                    ...       ...   
2684954  Deer Stags Kid's Brilliant Dress Comfort Oxfor...      None   
2684955                       Dansko Women's Honor Sneaker      None   
2684979               Columbia PFG Mesh Snap Back Ball Cap  Columbia   
2684987  adidas Originals Men's Tubular Shadow Fashion ...      None   
2685059  CUPSHE Women's Point Me at The Sky Floral Biki...    CUPSHE   

                  main_cat                                               rank  \
id                                                                              
47                    None                     87,615inClothing,ShoesJewelry(   
144                   None                     15,484inClothing,ShoesJewelry(   
284           Toys & Games                                               None   
316           Toys & Games                                               None   
333                   None  >#3,164 in Patio, Lawn & Garden (See Top 100 i...   
...                    ...                                                ...   
2684954               None                    343,935inClothing,ShoesJewelry(   
2684955               None                     44,554inClothing,ShoesJewelry(   
2684979  Sports & Outdoors                             5,346inSportsOutdoors(   
2684987               None                     74,828inClothing,ShoesJewelry(   
2685059               None                  1,142,909inClothing,ShoesJewelry(   

                    price                                         image_slug  \
id                                                                             
47                   None  [51HJbA8UG2L, 51FufN7RbSL, 51vKjwQ6eAL, 410fEp...   
144       $23.99 - $29.99  [41MAnSZ8QTL, 51qL9W098pL, 51QWVSqlAML, 51eOan...   
284                 $4.99                                      [21VAYWoNedL]   
316                 $7.41                                    [31y%2BZwVQJJL]   
333                  None  [51g%2BtUP7YSL, 41Jn0zjKRuL, 41ElBt2gWdL, 31Aw...   
...                   ...                                                ...   
2684954   $16.80 - $40.00  [51Q9Np4I4OL, 41JgD3Klb6L, 31hD-OLssoL, 41ABLP...   
2684955  $74.93 - $221.43  [51wGv%2BSmTHL, 41AE5SULqtL, 311xxeLqZ2L, 41Js...   
2684979            $20.90  [51cajtyCrBL, 416yFSOGLdL, 41t%2Bt3iFPYL, 513t...   
2684987  $48.45 - $199.00  [51wvO%2BYYxLL, 51VDqEjkM1L, 31Pab7SYh7L, 41gg...   
2685059              None  [6159EIP7QRL, 61XIz3dDNTL, 51YfL4EOAtL, 61DuK0...   

                    

In [78]:
some_products.loc[some_products['asin'] == 'B0105V2DEY'].iloc[0].title

'Slim Compact Leather Key Holder Wallet Pouch Gifts Him Her Men Women'

In [80]:
some_products.loc[some_products['asin'] == 'B0105V2DEY'].iloc[0]

asin                                                  B0105V2DEY
description                                                 None
title          Slim Compact Leather Key Holder Wallet Pouch G...
brand                                                Rustic Town
main_cat                                         Office Products
rank                             788,760inClothing,ShoesJewelry(
price                                                       None
image_slug     [41%2B7pqP-ZHL, 514%2BxE-dulL, 41xjNc9npzL, 51...
image_url      [https://images-na.ssl-images-amazon.com/image...
feature        [Leather, Imported, Soft and Supple Feel of a ...
category       [Clothing, Shoes & Jewelry, Men, Accessories, ...
tech_detail                                                 None
Name: 1997316, dtype: object